apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "inalix.fullname" . }}-worker
  namespace: {{ .Values.systemNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/worker/
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: image.tag
          value: v3-new
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0].host
          value: {{ .Values.ingressHostname }}
        - name: env.DATABASE_URL
          value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
        - name: env.REDIS_URL
          value: redis://redis-master.inalix-system/1 # jb0d8AXz9S
      values: |
        imagePullSecrets:
          {{- toYaml .Values.imagePullSecrets | nindent 10 }}
  destination:
    namespace: {{ .Values.appNamespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
