apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-argocd
  namespace: inalix-base
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: local
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
