
server:
  insecure: true
  ingress:
    enabled: true
    hostname: argocd.local.gd

redis:
  master:
    persistence:
      size: 1Gi

  replica:
    replicaCount: 2
    persistence:
      size: 1Gi

  architecture: replication
