apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fids
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      version: v3
      parameters:
        - name: webapp.ingress.hosts[0].host
          value: 10-11-1-31.nip.io
      values: |
        ingressHotsname: test.10-11-1-31.nip.io

        webapp:
          enabled: true
          ingress:
            enabled: true
            hostname: fids-sub.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1

        daphne:
          enabled: true
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1

        worker:
          enabled: true
          ingress:
            hostname: flower.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
  destination:
    namespace: fids
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
