apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fids
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/dimasinalix/config-example.git
    targetRevision: dimas
    helm:
      version: v3
      parameters:
        - name: webapp.ingress.hosts[0].host
          value: 10-11-1-31.nip.io
      values: |
        ingressHotsname: test.10-11-1-31.nip.io

        webapp:
          enabled: true
          ingress:
            enabled: true
            hostname: fids.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
          - name: LOCAL_AIRPORT_NAME
            value: Sultan Hasanuddin International Airport
          - name: LOCAL_AIRPORT_ICAO
            value: WAAA
          - name: LOCAL_AIRPORT_LOCATION
            value: Makassar
          - name: INALIX_APPS
            value: inalix.flight inalix.flight_public inalix.info inalix.display inalix.devices inalix.device_led inalix.plugin_advertisement inalix.plugin_schedule inalix.plugin_clock inalix.weather inalix.input inalix.input.inxsync inalix.plugin_announcer
          - name: DEVICES_LICENSING
            value: false

        daphne:
          enabled: true
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1

        worker:
          enabled: true
          ingress:
            hostname: flower.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
  destination:
    namespace: fids
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
