apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.1
    chart: minio
    helm:
      version: v3
      parameters:
      - name: ingress.enabled
        value: 'true'
      - name: ingress.hostname
        value: minio.10-11-1-31.nip.io
      - name: persistence.size
        value: 1Gi
      - name: defaultBuckets
        value: "media, backup"
      - name: auth.rootUser
        value: inalix-admin

  destination:
    namespace: inalix-system
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
