apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dokuwiki-demo
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.1.5
    chart: dokuwiki
    helm:
      parameters:
      - name: ingress.enabled
        value: 'true'
      - name: ingress.hostname
        value: wiki.7f000101.nip.io
      - name: persistance.enabled
        value: 'false'
      - name: dokuwikiWikiName
        value: "Demo Wiki with argo"
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
