apiVersion: v2
name: worker
description: A Helm chart for inalix worker
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
- condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
  name: redis
  version: 18.0.4
