apiVersion: v2
name: worker
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
dependencies:
- condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
  name: redis
  version: 18.0.4
